-- CreateTable
CREATE TABLE "SiteDesign" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "headerLogoImage" TEXT,
    "headerLogoText" TEXT NOT NULL DEFAULT 'ScriptOverNovel',
    "headerLogoFontFamily" TEXT NOT NULL DEFAULT 'var(--font-caveat), cursive',
    "headerLogoFontSize" TEXT NOT NULL DEFAULT '2rem',
    "headerLogoHeight" TEXT NOT NULL DEFAULT '40px',
    "headerBgColor" TEXT NOT NULL DEFAULT '#F2EFE6',
    "headerTextColor" TEXT NOT NULL DEFAULT '#0D0D0D',
    "headerMenuLabel" TEXT NOT NULL DEFAULT 'MENU',
    "headerShowSearch" BOOLEAN NOT NULL DEFAULT true,
    "headerShowThemeToggle" BOOLEAN NOT NULL DEFAULT false,
    "headerShowWishlist" BOOLEAN NOT NULL DEFAULT false,
    "headerShowCart" BOOLEAN NOT NULL DEFAULT false,
    "headerShowReleaseNotes" BOOLEAN NOT NULL DEFAULT false,
    "menuFontFamily" TEXT NOT NULL DEFAULT 'var(--font-playfair), Georgia, serif',
    "menuFontSize" TEXT NOT NULL DEFAULT '6rem',
    "menuFontSizeMobile" TEXT NOT NULL DEFAULT '3.25rem',
    "menuFontWeight" TEXT NOT NULL DEFAULT '900',
    "menuFontStyle" TEXT NOT NULL DEFAULT 'normal',
    "menuTextTransform" TEXT NOT NULL DEFAULT 'uppercase',
    "menuLetterSpacing" TEXT NOT NULL DEFAULT '-0.03em',
    "menuLineHeight" DOUBLE PRECISION NOT NULL DEFAULT 1,
    "menuTextColor" TEXT NOT NULL DEFAULT '#141414',
    "menuBgColor" TEXT NOT NULL DEFAULT '#F5D480',
    "menuImage" TEXT,
    "menuPanelWidth" INTEGER NOT NULL DEFAULT 50,
    "menuCloseBgColor" TEXT NOT NULL DEFAULT '#FFFFFF',
    "menuCloseIconColor" TEXT NOT NULL DEFAULT '#0D0D0D',
    "menuFooterText" TEXT NOT NULL DEFAULT 'JOIN THE MAILING LIST',
    "menuFooterHref" TEXT NOT NULL DEFAULT '/contact',
    "menuShowSocialLinks" BOOLEAN NOT NULL DEFAULT true,
    "menuSocialIconColor" TEXT NOT NULL DEFAULT '#141414',
    "heroEnabled" BOOLEAN NOT NULL DEFAULT true,
    "heroBgColor" TEXT NOT NULL DEFAULT '#F2EFE6',
    "heroImage" TEXT,
    "heroImageWidth" TEXT NOT NULL DEFAULT '480px',
    "heroHeading" TEXT NOT NULL DEFAULT 'The new collection',
    "heroHeadingFontFamily" TEXT NOT NULL DEFAULT 'var(--font-playfair), Georgia, serif',
    "heroHeadingFontSize" TEXT NOT NULL DEFAULT '3rem',
    "heroHeadingFontWeight" TEXT NOT NULL DEFAULT '700',
    "heroHeadingColor" TEXT NOT NULL DEFAULT '#141414',
    "heroSubheading" TEXT NOT NULL DEFAULT '',
    "heroCtaLabel" TEXT NOT NULL DEFAULT 'VIEW NOW',
    "heroCtaHref" TEXT NOT NULL DEFAULT '/gallery',
    "heroCtaBgColor" TEXT NOT NULL DEFAULT '#141414',
    "heroCtaTextColor" TEXT NOT NULL DEFAULT '#FFFFFF',
    "heroDecorImage" TEXT,
    "heroDecorPosition" TEXT NOT NULL DEFAULT 'bottom-left',
    "heroDecorWidth" TEXT NOT NULL DEFAULT '96px',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SiteDesign_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SiteMenuItem" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "href" TEXT NOT NULL,
    "bgColor" TEXT NOT NULL DEFAULT '#F5D480',
    "underlineColor" TEXT NOT NULL DEFAULT '#FDA063',
    "underlineStyle" TEXT NOT NULL DEFAULT 'scribble',
    "image" TEXT,
    "openInNewTab" BOOLEAN NOT NULL DEFAULT false,
    "isVisible" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SiteMenuItem_pkey" PRIMARY KEY ("id")
);
